"""create tables

Revision ID: 35b2493c0ce7
Revises: 
Create Date: 2025-08-28 23:15:13.549179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '35b2493c0ce7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('facebook', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', name='genderenum'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('week',
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('week')
    op.drop_table('user')
    # ### end Alembic commands ###
