"""create match day lineup table

Revision ID: 67f6dbe383dd
Revises: 35b2493c0ce7
Create Date: 2025-08-29 00:05:54.259535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '67f6dbe383dd'
down_revision: Union[str, Sequence[str], None] = '35b2493c0ce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matchdaylineup',
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['week_id'], ['week.id'], ),
    sa.PrimaryKeyConstraint('week_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matchdaylineup')
    # ### end Alembic commands ###
