"""add paid attribute

Revision ID: acdbc5fa26cd
Revises: 67f6dbe383dd
Create Date: 2025-09-25 10:36:04.178302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'acdbc5fa26cd'
down_revision: Union[str, Sequence[str], None] = '67f6dbe383dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_paid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_paid')
    # ### end Alembic commands ###
