"""add last login column

Revision ID: cda0a8cd1ba4
Revises: 698826e9172c
Create Date: 2025-08-26 23:37:58.220034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'cda0a8cd1ba4'
down_revision: Union[str, Sequence[str], None] = '698826e9172c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('week', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('week', 'date')
    op.drop_column('user', 'last_login')
    # ### end Alembic commands ###
